{{ if not .Values.keystone.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-keystone-db
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: keystone-db
type: Opaque
data:
  password: {{ required "password required!" .Values.keystoneDb.password | b64enc | quote }}
{{ end -}}
