{{ if .Values.rendersvc.enable -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "sciserver.fullname" . }}-render
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rendersvc
spec:
  selector:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rendersvc
  ports:
  - name: webapp
    protocol: TCP
    port: 8080
    targetPort: web
{{ end -}}