{{ if and .Values.keycloak.enabled (not .Values.keycloak.url) (not .Values.keycloak.db.host) (not .Values.dev.nopvc) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sciserver.fullname" . }}-keycloak-db
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.storageClass -}}
  storageClassName: {{ .Values.storageClass }}
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.keycloak.db.storage | quote }}
{{ end -}}
