package edu.jhu;

/**
 * Version class for scis :
 *
 * This is the data model for the SciServe rmetadata.
 *
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public interface ModelVersion {

    /** last modification date of the UML model */
    public final static long LAST_MODIFICATION_DATE = 1715110381549l;

}
