{{ if not .Values.keystone.host -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sciserver.fullname" . }}-keystone
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: keystone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sciserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: keystone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sciserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: keystone
    spec:
      hostname: keystone
      {{ if .Values.imagePullSecret -}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{ end -}}
      containers:
      - image: "{{ .Values.keystone.image.repository }}:{{ required "please specify keystone image tag or use image manifest" .Values.keystone.image.tag }}"
        name: keystone
        imagePullPolicy: {{ .Values.keystone.image.pullPolicy }}
        resources:
          {{- toYaml .Values.keystone.resources | nindent 10 }}
        env:
        - name: MYSQL_HOST
          {{- if .Values.keystoneDb.host }}
          value: {{ .Values.keystoneDb.host }}
          {{- else }}
          value: {{ include "sciserver.fullname" . }}-keystone-db
          {{- end }}
        - name: MYSQL_DATABASE
          value: {{ .Values.keystoneDb.name | quote }}
        - name: MYSQL_SSL
          value: {{ default "FALSE" .Values.keystoneDb.useSSL | quote }}
        - name: MYSQL_USER
          value: {{ .Values.keystoneDb.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone-db
                  key: password
        - name: KS_SERVER_NAME
          value: {{ include "sciserver.fullname" . }}-keystone
        - name: KS_ADMIN_TOKEN
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone
                  key: admin-token
        - name: KS_ADMIN_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone
                  key: admin-password
        - name: KS_DEMO_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone
                  key: demo-password
        - name: _CONFIG_HASH
          value: {{ include (print $.Template.BasePath "/keystone/service/keystone-secret.yaml") . | sha256sum }}-{{ include (print $.Template.BasePath "/keystone/db/keystone-db-secret.yaml") . | sha256sum }}
{{ if .Values.keycloak.enabled }}
        - name: KEYCLOAK_TRUST_PASS
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone
                  key: keycloaktrust-password
{{ end }}
{{ if .Values.casjobs.enable }}
        - name: CASJOBS_TRUST_PASS
          valueFrom:
              secretKeyRef:
                  name: {{ include "sciserver.fullname" . }}-keystone
                  key: casjobs-trust-password
        - name: CASJOBS_TRUST_USER
          value: {{ .Values.casjobs.keystone.admin_user }}
        - name: CASJOBS_TRUST_PROJECT
          value: {{ .Values.casjobs.keystone.admin_project }}
{{ end }}
        ports:
        - containerPort: 5000
          name: public
        readinessProbe:
          httpGet:
            path: /v3
            port: public
{{ end -}}
