apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-keystone
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: keystone
type: Opaque
data:
  admin-password: {{ required "password required!" .Values.keystone.admin.password | b64enc | quote }}
  admin-token: {{ .Values.keystone.admin.token | b64enc | quote }}
  demo-password: {{ required "password required!" .Values.keystone.demo.password | b64enc | quote }}
  keycloaktrust-password: {{ required "password required!" .Values.loginPortal.keycloakTrustPass | b64enc | quote }}
  casjobs-trust-password: {{ required "password required!" .Values.casjobs.keystone.admin_password | b64enc | quote }}
