{{ if .Values.logging.listener.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-log-listener
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: log-listener
type: Opaque
data:
  application.properties: {{ tpl (.Files.Get "files/log-listener-application.properties") . | b64enc }}
{{ end -}}
