apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-logging-api
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: logging-api
type: Opaque
data:
  application.properties: {{ tpl (.Files.Get "files/logging-api-application.properties") . | b64enc }}
