/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.file;

import java.util.Date;

import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.MetadataRootEntityObject;
import edu.jhu.rac.Resource;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object DataVolume :
 *
 * descirp
 *
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_DataVolume")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "DataVolume.findById", query = "SELECT o FROM DataVolume o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "DataVolume.findByPublisherDID", query = "SELECT o FROM DataVolume o WHERE o.identity.publisherDID = :publisherDID")

        ,
        @javax.persistence.NamedQuery(name = "DataVolume.findByName", query = "SELECT o FROM DataVolume o WHERE o.name = :name")

})

public class DataVolume extends MetadataRootEntityObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /**
     * Attribute name :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "name", nullable = false)

    private String name;

    /**
     * Attribute description :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 , MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = true) @javax.persistence.Lob @javax.persistence.Column(name = "description", nullable = true)

    private String description;

    /**
     * Attribute displayName :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "displayName", nullable = false)

    private String displayName;

    /**
     * Attribute pathOnFileSystem :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "pathOnFileSystem", nullable = false)

    private String pathOnFileSystem;

    /**
     * Attribute url :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "url", nullable = true)

    private String url;

    /**
     * Reference resource :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "resourceId", referencedColumnName = "id", nullable = false)

    private Resource resource = null;
    /**
     * "lazy" version of the resource reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource Resource.
     */

    @javax.persistence.Transient

    protected Reference p_resource = null;

    /**
     * Reference fileService :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "fileServiceId", referencedColumnName = "id", nullable = false)

    private FileService fileService = null;
    /**
     * "lazy" version of the fileService reference. Used by XML (un)marshallers to resolve possibly inderectly
     * referenced resource FileService.
     */

    @javax.persistence.Transient

    protected Reference p_fileService = null;

    /**
     * Creates a new DataVolume.
     */
    protected DataVolume() {
        super();
    }

    /**
     * Creates a new DataVolume for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public DataVolume(final TransientObjectManager pContainer) {
        super(pContainer);
    }

    /**
     * Returns name Attribute
     * 
     * @return name Attribute
     */
    public String getName() {
        return this.name;
    }

    /**
     * Defines name Attribute
     * 
     * @param pName value to set
     */
    public void setName(final String pName) {
        this.name = pName;
    }

    /**
     * Returns description Attribute
     * 
     * @return description Attribute
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Defines description Attribute
     * 
     * @param pDescription value to set
     */
    public void setDescription(final String pDescription) {
        this.description = pDescription;
    }

    /**
     * Returns displayName Attribute
     * 
     * @return displayName Attribute
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Defines displayName Attribute
     * 
     * @param pDisplayName value to set
     */
    public void setDisplayName(final String pDisplayName) {
        this.displayName = pDisplayName;
    }

    /**
     * Returns pathOnFileSystem Attribute
     * 
     * @return pathOnFileSystem Attribute
     */
    public String getPathOnFileSystem() {
        return this.pathOnFileSystem;
    }

    /**
     * Defines pathOnFileSystem Attribute
     * 
     * @param pPathOnFileSystem value to set
     */
    public void setPathOnFileSystem(final String pPathOnFileSystem) {
        this.pathOnFileSystem = pPathOnFileSystem;
    }

    /**
     * Returns url Attribute
     * 
     * @return url Attribute
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Defines url Attribute
     * 
     * @param pUrl value to set
     */
    public void setUrl(final String pUrl) {
        this.url = pUrl;
    }

    /**
     * Returns resource Reference If the resource variable is null but its "lazy" version p_resource is not, that lazy
     * reference will be resolved to the actual object.
     * 
     * @return resource Reference
     */
    public Resource getResource() {

        if (this.resource == null && this.p_resource != null) {
            this.resource = (Resource) resolve(this.p_resource, Resource.class);
        }
        return this.resource;

    }

    /**
     * Defines resource Reference
     * 
     * @param pResource reference to set
     */
    public void setResource(final Resource pResource) {

        this.resource = pResource;

    }

    /**
     * Returns fileService Reference If the fileService variable is null but its "lazy" version p_fileService is not,
     * that lazy reference will be resolved to the actual object.
     * 
     * @return fileService Reference
     */
    public FileService getFileService() {

        if (this.fileService == null && this.p_fileService != null) {
            this.fileService = (FileService) resolve(this.p_fileService, FileService.class);
        }
        return this.fileService;

    }

    /**
     * Defines fileService Reference
     * 
     * @param pFileService reference to set
     */
    public void setFileService(final FileService pFileService) {

        this.fileService = pFileService;

    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final DataVolume other = (DataVolume) object;

            if (!areEquals(this.name, other.name)) {
                return false;
            }

            if (!areEquals(this.description, other.description)) {
                return false;
            }

            if (!areEquals(this.displayName, other.displayName)) {
                return false;
            }

            if (!areEquals(this.pathOnFileSystem, other.pathOnFileSystem)) {
                return false;
            }

            if (!areEquals(this.url, other.url)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if ("name".equals(propertyName)) {
            return getName();
        }

        if ("description".equals(propertyName)) {
            return getDescription();
        }

        if ("displayName".equals(propertyName)) {
            return getDisplayName();
        }

        if ("pathOnFileSystem".equals(propertyName)) {
            return getPathOnFileSystem();
        }

        if ("url".equals(propertyName)) {
            return getUrl();
        }

        if ("resource".equals(propertyName)) {
            return getResource();
        }

        if ("fileService".equals(propertyName)) {
            return getFileService();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if ("name".equals(propertyName)) {
                setName((String) pValue);
                return true;
            }

            if ("description".equals(propertyName)) {
                setDescription((String) pValue);
                return true;
            }

            if ("displayName".equals(propertyName)) {
                setDisplayName((String) pValue);
                return true;
            }

            if ("pathOnFileSystem".equals(propertyName)) {
                setPathOnFileSystem((String) pValue);
                return true;
            }

            if ("url".equals(propertyName)) {
                setUrl((String) pValue);
                return true;
            }

            if ("resource".equals(propertyName)) {
                setResource((Resource) pValue);
                return true;
            }

            if ("fileService".equals(propertyName)) {
                setFileService((FileService) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getResource() != null) {
            this.p_resource = getResource().asReference();
            if (getStateFor(getResource()).isToBeMarshalled()) {
                getResource().setXmlId();
            }
        }

        if (getFileService() != null) {
            this.p_fileService = getFileService().asReference();
            if (getStateFor(getFileService()).isToBeMarshalled()) {
                getFileService().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_resource = null;

        this.p_fileService = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ DataVolume");
        sb.append("={");

        sb.append("name=");
        if (getName() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getName());
        }
        sb.append(", ");
        sb.append("description=");
        if (getDescription() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getDescription());
        }
        sb.append(", ");
        sb.append("displayName=");
        if (getDisplayName() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getDisplayName());
        }
        sb.append(", ");
        sb.append("pathOnFileSystem=");
        if (getPathOnFileSystem() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getPathOnFileSystem());
        }
        sb.append(", ");
        sb.append("url=");
        if (getUrl() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getUrl());
        }
        sb.append(", ");
        sb.append("resource.id=");
        if (getResource() != null) {
            getResource().getId();
        }
        sb.append(", ");
        sb.append("fileService.id=");
        if (getFileService() != null) {
            getFileService().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && name != null;
        isOk = isOk && displayName != null;
        isOk = isOk && pathOnFileSystem != null;
        isOk = isOk && (resource != null || p_resource != null);
        isOk = isOk && (fileService != null || p_fileService != null);
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (name == null)
            sb.append("- atribute 'name' cannot be null\n");

        if (displayName == null)
            sb.append("- atribute 'displayName' cannot be null\n");

        if (pathOnFileSystem == null)
            sb.append("- atribute 'pathOnFileSystem' cannot be null\n");

        if (resource == null && p_resource == null)
            sb.append("- reference 'resource' cannot be null\n");

        if (fileService == null && p_fileService == null)
            sb.append("- reference 'fileService' cannot be null\n");

        return sb.toString();
    }

}
