/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.file;

import java.util.Date;

import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.IMetadataObjectContainer;

import edu.jhu.rac.Resource;

import edu.jhu.user.User;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object UserVolume :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_UserVolume")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "UserVolume.findById", query = "SELECT o FROM UserVolume o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "UserVolume.findByPublisherDID", query = "SELECT o FROM UserVolume o WHERE o.identity.publisherDID = :publisherDID")

        ,
        @javax.persistence.NamedQuery(name = "UserVolume.findByName", query = "SELECT o FROM UserVolume o WHERE o.name = :name")

})

public class UserVolume extends MetadataObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /** container gives the parent entity which owns a collection containing instances of this class */
    @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }, fetch = javax.persistence.FetchType.LAZY) @javax.persistence.JoinColumn(name = "containerId", referencedColumnName = "id", nullable = false)
    protected FileService container;

    /**
     * Attribute relativePath : The relative path from RootVolume's fileServicePath to the location of this volume on
     * the file service. ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "relativePath", nullable = false)

    private String relativePath;

    /**
     * Attribute description :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 , MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = true) @javax.persistence.Lob @javax.persistence.Column(name = "description", nullable = true)

    private String description;

    /**
     * Attribute name :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "name", nullable = true)

    private String name;

    /**
     * Reference resource :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "resourceId", referencedColumnName = "id", nullable = false)

    private Resource resource = null;
    /**
     * "lazy" version of the resource reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource Resource.
     */

    @javax.persistence.Transient

    protected Reference p_resource = null;

    /**
     * Reference rootVolume :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "rootVolumeId", referencedColumnName = "id", nullable = false)

    private RootVolume rootVolume = null;
    /**
     * "lazy" version of the rootVolume reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource RootVolume.
     */

    @javax.persistence.Transient

    protected Reference p_rootVolume = null;

    /**
     * Reference owner :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "ownerId", referencedColumnName = "id", nullable = false)

    private User owner = null;
    /**
     * "lazy" version of the owner reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource User.
     */

    @javax.persistence.Transient

    protected Reference p_owner = null;

    /**
     * Creates a new UserVolume.
     */
    protected UserVolume() {
        super();
    }

    /**
     * Creates a new UserVolume for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public UserVolume(final FileService pContainer) {
        super();
        this.setContainer(pContainer);
    }

    /**
     * Returns relativePath Attribute
     * 
     * @return relativePath Attribute
     */
    public String getRelativePath() {
        return this.relativePath;
    }

    /**
     * Defines relativePath Attribute
     * 
     * @param pRelativePath value to set
     */
    public void setRelativePath(final String pRelativePath) {
        this.relativePath = pRelativePath;
    }

    /**
     * Returns description Attribute
     * 
     * @return description Attribute
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Defines description Attribute
     * 
     * @param pDescription value to set
     */
    public void setDescription(final String pDescription) {
        this.description = pDescription;
    }

    /**
     * Returns name Attribute
     * 
     * @return name Attribute
     */
    public String getName() {
        return this.name;
    }

    /**
     * Defines name Attribute
     * 
     * @param pName value to set
     */
    public void setName(final String pName) {
        this.name = pName;
    }

    /**
     * Returns resource Reference If the resource variable is null but its "lazy" version p_resource is not, that lazy
     * reference will be resolved to the actual object.
     * 
     * @return resource Reference
     */
    public Resource getResource() {

        if (this.resource == null && this.p_resource != null) {
            this.resource = (Resource) resolve(this.p_resource, Resource.class);
        }
        return this.resource;

    }

    /**
     * Defines resource Reference
     * 
     * @param pResource reference to set
     */
    public void setResource(final Resource pResource) {

        this.resource = pResource;

    }

    /**
     * Returns rootVolume Reference If the rootVolume variable is null but its "lazy" version p_rootVolume is not, that
     * lazy reference will be resolved to the actual object.
     * 
     * @return rootVolume Reference
     */
    public RootVolume getRootVolume() {

        if (this.rootVolume == null && this.p_rootVolume != null) {
            this.rootVolume = (RootVolume) resolve(this.p_rootVolume, RootVolume.class);
        }
        return this.rootVolume;

    }

    /**
     * Defines rootVolume Reference
     * 
     * @param pRootVolume reference to set
     */
    public void setRootVolume(final RootVolume pRootVolume) {

        this.rootVolume = pRootVolume;

    }

    /**
     * Returns owner Reference If the owner variable is null but its "lazy" version p_owner is not, that lazy reference
     * will be resolved to the actual object.
     * 
     * @return owner Reference
     */
    public User getOwner() {

        if (this.owner == null && this.p_owner != null) {
            this.owner = (User) resolve(this.p_owner, User.class);
        }
        return this.owner;

    }

    /**
     * Defines owner Reference
     * 
     * @param pOwner reference to set
     */
    public void setOwner(final User pOwner) {

        this.owner = pOwner;

    }

    /**
     * Returns the Container Entity == 'Parent'.
     * 
     * @return the parent container Entity
     */
    public FileService getContainer() {
        return this.container;
    }

    @Override
    public IMetadataObjectContainer container() {
        return getContainer();
    }

    /**
     * Sets the Container Entity == 'Parent' ONLY.
     * 
     * @param pContainer the parent container
     */
    private void setContainerField(final FileService pContainer) {
        this.container = pContainer;
    }

    /**
     * Sets the Container Entity == 'Parent' and adds this to the appropriate collection on the container.
     *
     * @param pContainer the parent container CAN NOT BE NULL
     *
     * @throws IllegalStateException if pContainer is null !
     */
    protected void setContainer(final FileService pContainer) {
        if (pContainer == null) {
            throw new IllegalStateException("The parent container can not be null !");
        }
        setContainerField(pContainer);
        pContainer.addUserVolumes(this);
    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final UserVolume other = (UserVolume) object;

            if (!areEquals(this.relativePath, other.relativePath)) {
                return false;
            }

            if (!areEquals(this.description, other.description)) {
                return false;
            }

            if (!areEquals(this.name, other.name)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if (PROPERTY_CONTAINER.equals(propertyName)) {
            return getContainer();
        }

        if ("relativePath".equals(propertyName)) {
            return getRelativePath();
        }

        if ("description".equals(propertyName)) {
            return getDescription();
        }

        if ("name".equals(propertyName)) {
            return getName();
        }

        if ("resource".equals(propertyName)) {
            return getResource();
        }

        if ("rootVolume".equals(propertyName)) {
            return getRootVolume();
        }

        if ("owner".equals(propertyName)) {
            return getOwner();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if (PROPERTY_CONTAINER.equals(propertyName)) {
                setContainerField((FileService) pValue);
                return true;
            }

            if ("relativePath".equals(propertyName)) {
                setRelativePath((String) pValue);
                return true;
            }

            if ("description".equals(propertyName)) {
                setDescription((String) pValue);
                return true;
            }

            if ("name".equals(propertyName)) {
                setName((String) pValue);
                return true;
            }

            if ("resource".equals(propertyName)) {
                setResource((Resource) pValue);
                return true;
            }

            if ("rootVolume".equals(propertyName)) {
                setRootVolume((RootVolume) pValue);
                return true;
            }

            if ("owner".equals(propertyName)) {
                setOwner((User) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getResource() != null) {
            this.p_resource = getResource().asReference();
            if (getStateFor(getResource()).isToBeMarshalled()) {
                getResource().setXmlId();
            }
        }

        if (getRootVolume() != null) {
            this.p_rootVolume = getRootVolume().asReference();
            if (getStateFor(getRootVolume()).isToBeMarshalled()) {
                getRootVolume().setXmlId();
            }
        }

        if (getOwner() != null) {
            this.p_owner = getOwner().asReference();
            if (getStateFor(getOwner()).isToBeMarshalled()) {
                getOwner().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_resource = null;

        this.p_rootVolume = null;

        this.p_owner = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ UserVolume");
        sb.append("={");

        sb.append("container=");
        if (getContainer() != null) {
            // short toString :
            MetadataElement.deepToString(sb, false, ids, getContainer());
        }
        sb.append(" | ");

        sb.append("relativePath=");
        if (getRelativePath() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getRelativePath());
        }
        sb.append(", ");
        sb.append("description=");
        if (getDescription() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getDescription());
        }
        sb.append(", ");
        sb.append("name=");
        if (getName() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getName());
        }
        sb.append(", ");
        sb.append("resource.id=");
        if (getResource() != null) {
            getResource().getId();
        }
        sb.append(", ");
        sb.append("rootVolume.id=");
        if (getRootVolume() != null) {
            getRootVolume().getId();
        }
        sb.append(", ");
        sb.append("owner.id=");
        if (getOwner() != null) {
            getOwner().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && relativePath != null;
        isOk = isOk && (resource != null || p_resource != null);
        isOk = isOk && (rootVolume != null || p_rootVolume != null);
        isOk = isOk && (owner != null || p_owner != null);
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (relativePath == null)
            sb.append("- atribute 'relativePath' cannot be null\n");

        if (resource == null && p_resource == null)
            sb.append("- reference 'resource' cannot be null\n");

        if (rootVolume == null && p_rootVolume == null)
            sb.append("- reference 'rootVolume' cannot be null\n");

        if (owner == null && p_owner == null)
            sb.append("- reference 'owner' cannot be null\n");

        return sb.toString();
    }

}
