/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting the code
**/
package edu.jhu.rac;

import javax.xml.bind.annotation.*;

/**
 * UML Enumeration ActionCategory.
 *
 * Type of action, based on CRUD+Grant. Can be used to categorize a cusotm-named action. Particularly useful for delete
 * and grant.
 *
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public enum ActionCategory {

    /**
     * Value C :
     * 
     * create-like action
     */
    C("C"),

    /**
     * Value R :
     * 
     * read-like action
     */
    R("R"),

    /**
     * Value U :
     * 
     * update-like action
     */
    U("U"),

    /**
     * Value D :
     * 
     * delete-like action
     */
    D("D"),

    /**
     * Value G :
     * 
     * grant-like action
     */
    G("G"),

    /**
     * Value X :
     * 
     * Action indicating some kind of execution, of a query or other type of job.
     */
    X("X");

    /** string representation */
    private final String value;

    /**
     * Creates a new ActionCategory Enumeration Literal
     *
     * @param v string representation
     */
    ActionCategory(final String v) {
        value = v;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @return string representation of this enum constant (value)
     */
    public final String value() {
        return this.value;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @see #value()
     * @return string representation of this enum constant (value)
     */
    @Override
    public final String toString() {
        return value();
    }

    /**
     * Return the ActionCategory enum constant corresponding to the given string representation (value)
     *
     * @param v string representation (value)
     *
     * @return ActionCategory enum constant
     *
     * @throws IllegalArgumentException if there is no matching enum constant
     */
    public final static ActionCategory fromValue(final String v) {
        for (ActionCategory c : ActionCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException("ActionCategory.fromValue : No enum const for the value : " + v);
    }

}
