/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.rac;

import java.util.Date;

import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.IMetadataObjectContainer;

import edu.jhu.user.SciserverEntity;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object AssociatedSciEntity :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_AssociatedSciEntity")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "AssociatedSciEntity.findById", query = "SELECT o FROM AssociatedSciEntity o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "AssociatedSciEntity.findByPublisherDID", query = "SELECT o FROM AssociatedSciEntity o WHERE o.identity.publisherDID = :publisherDID")

})

public class AssociatedSciEntity extends MetadataObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /** container gives the parent entity which owns a collection containing instances of this class */
    @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }, fetch = javax.persistence.FetchType.LAZY) @javax.persistence.JoinColumn(name = "containerId", referencedColumnName = "id", nullable = false)
    protected Resource container;

    /**
     * Attribute usage :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "usage", nullable = true)

    private String usage;

    /**
     * Attribute ownership :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Enumerated(javax.persistence.EnumType.STRING) @javax.persistence.Column(name = "ownership", nullable = true)

    private OwnershipCategory ownership;

    /**
     * Reference sciEntity :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "sciEntityId", referencedColumnName = "id", nullable = false)

    private SciserverEntity sciEntity = null;
    /**
     * "lazy" version of the sciEntity reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource SciserverEntity.
     */

    @javax.persistence.Transient

    protected Reference p_sciEntity = null;

    /**
     * Creates a new AssociatedSciEntity.
     */
    protected AssociatedSciEntity() {
        super();
    }

    /**
     * Creates a new AssociatedSciEntity for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public AssociatedSciEntity(final Resource pContainer) {
        super();
        this.setContainer(pContainer);
    }

    /**
     * Returns usage Attribute
     * 
     * @return usage Attribute
     */
    public String getUsage() {
        return this.usage;
    }

    /**
     * Defines usage Attribute
     * 
     * @param pUsage value to set
     */
    public void setUsage(final String pUsage) {
        this.usage = pUsage;
    }

    /**
     * Returns ownership Attribute
     * 
     * @return ownership Attribute
     */
    public OwnershipCategory getOwnership() {
        return this.ownership;
    }

    /**
     * Defines ownership Attribute
     * 
     * @param pOwnership value to set
     */
    public void setOwnership(final OwnershipCategory pOwnership) {
        this.ownership = pOwnership;
    }

    /**
     * Returns sciEntity Reference If the sciEntity variable is null but its "lazy" version p_sciEntity is not, that
     * lazy reference will be resolved to the actual object.
     * 
     * @return sciEntity Reference
     */
    public SciserverEntity getSciEntity() {

        if (this.sciEntity == null && this.p_sciEntity != null) {
            this.sciEntity = (SciserverEntity) resolve(this.p_sciEntity, SciserverEntity.class);
        }
        return this.sciEntity;

    }

    /**
     * Defines sciEntity Reference
     * 
     * @param pSciEntity reference to set
     */
    public void setSciEntity(final SciserverEntity pSciEntity) {

        this.sciEntity = pSciEntity;

    }

    /**
     * Returns the Container Entity == 'Parent'.
     * 
     * @return the parent container Entity
     */
    public Resource getContainer() {
        return this.container;
    }

    @Override
    public IMetadataObjectContainer container() {
        return getContainer();
    }

    /**
     * Sets the Container Entity == 'Parent' ONLY.
     * 
     * @param pContainer the parent container
     */
    private void setContainerField(final Resource pContainer) {
        this.container = pContainer;
    }

    /**
     * Sets the Container Entity == 'Parent' and adds this to the appropriate collection on the container.
     *
     * @param pContainer the parent container CAN NOT BE NULL
     *
     * @throws IllegalStateException if pContainer is null !
     */
    protected void setContainer(final Resource pContainer) {
        if (pContainer == null) {
            throw new IllegalStateException("The parent container can not be null !");
        }
        setContainerField(pContainer);
        pContainer.addAssociatedGroup(this);
    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final AssociatedSciEntity other = (AssociatedSciEntity) object;

            if (!areEquals(this.usage, other.usage)) {
                return false;
            }

            if (!areEquals(this.ownership, other.ownership)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if (PROPERTY_CONTAINER.equals(propertyName)) {
            return getContainer();
        }

        if ("usage".equals(propertyName)) {
            return getUsage();
        }

        if ("ownership".equals(propertyName)) {
            return getOwnership();
        }

        if ("sciEntity".equals(propertyName)) {
            return getSciEntity();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if (PROPERTY_CONTAINER.equals(propertyName)) {
                setContainerField((Resource) pValue);
                return true;
            }

            if ("usage".equals(propertyName)) {
                setUsage((String) pValue);
                return true;
            }

            if ("ownership".equals(propertyName)) {
                setOwnership((OwnershipCategory) pValue);
                return true;
            }

            if ("sciEntity".equals(propertyName)) {
                setSciEntity((SciserverEntity) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getSciEntity() != null) {
            this.p_sciEntity = getSciEntity().asReference();
            if (getStateFor(getSciEntity()).isToBeMarshalled()) {
                getSciEntity().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_sciEntity = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ AssociatedSciEntity");
        sb.append("={");

        sb.append("container=");
        if (getContainer() != null) {
            // short toString :
            MetadataElement.deepToString(sb, false, ids, getContainer());
        }
        sb.append(" | ");

        sb.append("usage=");
        if (getUsage() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getUsage());
        }
        sb.append(", ");
        sb.append("ownership=");
        if (getOwnership() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getOwnership());
        }
        sb.append(", ");
        sb.append("sciEntity.id=");
        if (getSciEntity() != null) {
            getSciEntity().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && (sciEntity != null || p_sciEntity != null);
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (sciEntity == null && p_sciEntity == null)
            sb.append("- reference 'sciEntity' cannot be null\n");

        return sb.toString();
    }

}
