/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.rac;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.MetadataRootEntityObject;
import edu.jhu.user.User;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object ContextClass :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_ContextClass")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "ContextClass.findById", query = "SELECT o FROM ContextClass o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "ContextClass.findByPublisherDID", query = "SELECT o FROM ContextClass o WHERE o.identity.publisherDID = :publisherDID")

        ,
        @javax.persistence.NamedQuery(name = "ContextClass.findByName", query = "SELECT o FROM ContextClass o WHERE o.name = :name")

})

public class ContextClass extends MetadataRootEntityObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /**
     * Attribute name :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "name", nullable = false)

    private String name;

    /**
     * Attribute description :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 , MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = true) @javax.persistence.Lob @javax.persistence.Column(name = "description", nullable = true)

    private String description;

    /**
     * Attribute release : INdicates the release of the application context. ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "release", nullable = true)

    private String release;

    /**
     * Collection resourceType :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..* )
     */

    @javax.persistence.OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.LAZY, mappedBy = "container", orphanRemoval = true)

    private List<ResourceType> resourceType = null;

    /**
     * Reference creator :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.ManyToOne(optional = true, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "creatorId", referencedColumnName = "id", nullable = true)

    private User creator = null;
    /**
     * "lazy" version of the creator reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource User.
     */

    @javax.persistence.Transient

    protected Reference p_creator = null;

    /**
     * Creates a new ContextClass.
     */
    protected ContextClass() {
        super();
    }

    /**
     * Creates a new ContextClass for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public ContextClass(final TransientObjectManager pContainer) {
        super(pContainer);
    }

    /**
     * Returns name Attribute
     * 
     * @return name Attribute
     */
    public String getName() {
        return this.name;
    }

    /**
     * Defines name Attribute
     * 
     * @param pName value to set
     */
    public void setName(final String pName) {
        this.name = pName;
    }

    /**
     * Returns description Attribute
     * 
     * @return description Attribute
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Defines description Attribute
     * 
     * @param pDescription value to set
     */
    public void setDescription(final String pDescription) {
        this.description = pDescription;
    }

    /**
     * Returns release Attribute
     * 
     * @return release Attribute
     */
    public String getRelease() {
        return this.release;
    }

    /**
     * Defines release Attribute
     * 
     * @param pRelease value to set
     */
    public void setRelease(final String pRelease) {
        this.release = pRelease;
    }

    /**
     * Returns resourceType Collection
     * 
     * @return resourceType Collection
     */
    public List<ResourceType> getResourceType() {
        return this.resourceType;
    }

    /**
     * Defines resourceType Collection
     * 
     * @param pResourceType collection to set
     */
    public void setResourceType(final List<ResourceType> pResourceType) {
        this.resourceType = pResourceType;
    }

    /**
     * Add a ResourceType to the collection
     * 
     * @param pResourceType ResourceType to add
     */
    public void addResourceType(final ResourceType pResourceType) {
        if (this.resourceType == null) {
            this.resourceType = new ArrayList<ResourceType>();
        }

        this.resourceType.add(pResourceType);
    }

    /**
     * Returns creator Reference If the creator variable is null but its "lazy" version p_creator is not, that lazy
     * reference will be resolved to the actual object.
     * 
     * @return creator Reference
     */
    public User getCreator() {

        if (this.creator == null && this.p_creator != null) {
            this.creator = (User) resolve(this.p_creator, User.class);
        }
        return this.creator;

    }

    /**
     * Defines creator Reference
     * 
     * @param pCreator reference to set
     */
    public void setCreator(final User pCreator) {

        this.creator = pCreator;

    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final ContextClass other = (ContextClass) object;

            if (!areEquals(this.name, other.name)) {
                return false;
            }

            if (!areEquals(this.description, other.description)) {
                return false;
            }

            if (!areEquals(this.release, other.release)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if ("name".equals(propertyName)) {
            return getName();
        }

        if ("description".equals(propertyName)) {
            return getDescription();
        }

        if ("release".equals(propertyName)) {
            return getRelease();
        }

        if ("resourceType".equals(propertyName)) {
            return getResourceType();
        }

        if ("creator".equals(propertyName)) {
            return getCreator();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if ("name".equals(propertyName)) {
                setName((String) pValue);
                return true;
            }

            if ("description".equals(propertyName)) {
                setDescription((String) pValue);
                return true;
            }

            if ("release".equals(propertyName)) {
                setRelease((String) pValue);
                return true;
            }

            if ("creator".equals(propertyName)) {
                setCreator((User) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getCreator() != null) {
            this.p_creator = getCreator().asReference();
            if (getStateFor(getCreator()).isToBeMarshalled()) {
                getCreator().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_creator = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ ContextClass");
        sb.append("={");

        sb.append("name=");
        if (getName() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getName());
        }
        sb.append(", ");
        sb.append("description=");
        if (getDescription() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getDescription());
        }
        sb.append(", ");
        sb.append("release=");
        if (getRelease() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getRelease());
        }
        sb.append(", ");
        sb.append("resourceType=");
        if (getResourceType() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getResourceType());
        }
        sb.append(", ");
        sb.append("creator.id=");
        if (getCreator() != null) {
            getCreator().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && name != null;
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (name == null)
            sb.append("- atribute 'name' cannot be null\n");

        return sb.toString();
    }

}
