apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-racm
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: racm
type: Opaque
data:
  application.yaml: {{ tpl (.Files.Get "files/racm-application.yaml") . | b64enc }}
  # Used for easy querying from NOTES.txt
  racm-admin-password: {{ required "password required!" .Values.racm.admin.password | b64enc }}
