apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-fileservice
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: fileservice
type: Opaque
data:
  application.properties: {{ tpl (.Files.Get "files/fileservice-application.properties") . | b64enc }}
  # Used for init-container
  serviceToken: {{ .Values.fileservice.serviceToken | b64enc }}
