kind: Service
apiVersion: v1
metadata:
  name: {{ include "sciserver.fullname" . }}-fileservice
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: fileservice
spec:
  selector:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: fileservice
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web
