{{ if not .Values.logging.rabbitmq.host -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-logging-rabbitmq
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: logging-rabbitmq
type: Opaque
data:
  erlang-cookie: {{ "adfasdfasdf" | b64enc | quote }}
{{ end -}}