{{ if not .Values.logging.rabbitmq.host -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sciserver.fullname" . }}-logging-rabbitmq
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: logging-rabbitmq
data:
  30-local.conf: |
    cluster_formation.peer_discovery_backend = classic_config
    cluster_formation.classic_config.nodes.1 = rabbit@{{ include "sciserver.fullname" . }}-logging-rabbitmq-0.{{ include "sciserver.fullname" . }}-logging-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
    {{- if gt (int .Values.logging.rabbitmq.replicaCount) 1 }}
    cluster_formation.classic_config.nodes.2 = rabbit@{{ include "sciserver.fullname" . }}-logging-rabbitmq-1.{{ include "sciserver.fullname" . }}-logging-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
    {{- end}}
    {{- if gt (int .Values.logging.rabbitmq.replicaCount) 2 }}
    cluster_formation.classic_config.nodes.3 = rabbit@{{ include "sciserver.fullname" . }}-logging-rabbitmq-2.{{ include "sciserver.fullname" . }}-logging-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
    {{- end}}
    {{- if gt (int .Values.logging.rabbitmq.replicaCount) 3 }}
    cluster_formation.classic_config.nodes.4 = rabbit@{{ include "sciserver.fullname" . }}-logging-rabbitmq-3.{{ include "sciserver.fullname" . }}-logging-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
    {{- end}}
    {{- if gt (int .Values.logging.rabbitmq.replicaCount) 4 }}
    cluster_formation.classic_config.nodes.5 = rabbit@{{ include "sciserver.fullname" . }}-logging-rabbitmq-4.{{ include "sciserver.fullname" . }}-logging-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
    {{- end}}
    {{- if gt (int .Values.logging.rabbitmq.replicaCount) 5 }}
    {{- fail "RabbitMQ replica count greater than 5 is not supported" }}
    {{- end }}
{{ end -}}