{{ if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-login-portal-db-pass
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: login-portal-db
type: Opaque
data:
  password: {{ required "password required!" .Values.loginPortal.db.pass | b64enc | quote }}
{{ end -}}
