{{ if and .Values.keycloak.enabled (not .Values.loginPortal.db.host) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sciserver.fullname" . }}-login-portal-db
spec:
  selector:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: login-portal-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
{{ end -}}
