/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.job;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.IMetadataObjectContainer;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object JobMessage :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_JobMessage")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "JobMessage.findById", query = "SELECT o FROM JobMessage o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "JobMessage.findByPublisherDID", query = "SELECT o FROM JobMessage o WHERE o.identity.publisherDID = :publisherDID")

})

public class JobMessage extends MetadataObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /** container gives the parent entity which owns a collection containing instances of this class */
    @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }, fetch = javax.persistence.FetchType.LAZY) @javax.persistence.JoinColumn(name = "containerId", referencedColumnName = "id", nullable = false)
    protected Job container;

    /**
     * Attribute content :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 , MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = true) @javax.persistence.Lob @javax.persistence.Column(name = "content", nullable = true)

    private String content;

    /**
     * Attribute label :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Enumerated(javax.persistence.EnumType.STRING) @javax.persistence.Column(name = "label", nullable = true)

    private MessageType label;

    /**
     * Collection response :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..* )
     */

    @javax.persistence.OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.LAZY, mappedBy = "container", orphanRemoval = true)

    private List<Response> response = null;

    /**
     * Creates a new JobMessage.
     */
    protected JobMessage() {
        super();
    }

    /**
     * Creates a new JobMessage for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public JobMessage(final Job pContainer) {
        super();
        this.setContainer(pContainer);
    }

    /**
     * Returns content Attribute
     * 
     * @return content Attribute
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Defines content Attribute
     * 
     * @param pContent value to set
     */
    public void setContent(final String pContent) {
        this.content = pContent;
    }

    /**
     * Returns label Attribute
     * 
     * @return label Attribute
     */
    public MessageType getLabel() {
        return this.label;
    }

    /**
     * Defines label Attribute
     * 
     * @param pLabel value to set
     */
    public void setLabel(final MessageType pLabel) {
        this.label = pLabel;
    }

    /**
     * Returns response Collection
     * 
     * @return response Collection
     */
    public List<Response> getResponse() {
        return this.response;
    }

    /**
     * Defines response Collection
     * 
     * @param pResponse collection to set
     */
    public void setResponse(final List<Response> pResponse) {
        this.response = pResponse;
    }

    /**
     * Add a Response to the collection
     * 
     * @param pResponse Response to add
     */
    public void addResponse(final Response pResponse) {
        if (this.response == null) {
            this.response = new ArrayList<Response>();
        }

        this.response.add(pResponse);
    }

    /**
     * Returns the Container Entity == 'Parent'.
     * 
     * @return the parent container Entity
     */
    public Job getContainer() {
        return this.container;
    }

    @Override
    public IMetadataObjectContainer container() {
        return getContainer();
    }

    /**
     * Sets the Container Entity == 'Parent' ONLY.
     * 
     * @param pContainer the parent container
     */
    private void setContainerField(final Job pContainer) {
        this.container = pContainer;
    }

    /**
     * Sets the Container Entity == 'Parent' and adds this to the appropriate collection on the container.
     *
     * @param pContainer the parent container CAN NOT BE NULL
     *
     * @throws IllegalStateException if pContainer is null !
     */
    protected void setContainer(final Job pContainer) {
        if (pContainer == null) {
            throw new IllegalStateException("The parent container can not be null !");
        }
        setContainerField(pContainer);
        pContainer.addMessage(this);
    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final JobMessage other = (JobMessage) object;

            if (!areEquals(this.content, other.content)) {
                return false;
            }

            if (!areEquals(this.label, other.label)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if (PROPERTY_CONTAINER.equals(propertyName)) {
            return getContainer();
        }

        if ("content".equals(propertyName)) {
            return getContent();
        }

        if ("label".equals(propertyName)) {
            return getLabel();
        }

        if ("response".equals(propertyName)) {
            return getResponse();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if (PROPERTY_CONTAINER.equals(propertyName)) {
                setContainerField((Job) pValue);
                return true;
            }

            if ("content".equals(propertyName)) {
                setContent((String) pValue);
                return true;
            }

            if ("label".equals(propertyName)) {
                setLabel((MessageType) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ JobMessage");
        sb.append("={");

        sb.append("container=");
        if (getContainer() != null) {
            // short toString :
            MetadataElement.deepToString(sb, false, ids, getContainer());
        }
        sb.append(" | ");

        sb.append("content=");
        if (getContent() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getContent());
        }
        sb.append(", ");
        sb.append("label=");
        if (getLabel() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getLabel());
        }
        sb.append(", ");
        sb.append("response=");
        if (getResponse() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getResponse());
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;

        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        return sb.toString();
    }

}
