/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting the code
**/
package edu.jhu.job;

import javax.xml.bind.annotation.*;

/**
 * UML Enumeration MessageType.
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public enum MessageType {

    /**
     * Value CANCEL :
     * 
     * Requests the job sould be cancelled.
     */
    CANCEL("CANCEL"),

    /**
     * Value STATUS :
     * 
     * Requests the status of the job.
     */
    STATUS("STATUS"),

    /**
     * Value RESPONSE :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    RESPONSE("RESPONSE"),

    /**
     * Value ERROR :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    ERROR("ERROR"),

    /**
     * Value TIMEOUT :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    TIMEOUT("TIMEOUT"),

    /**
     * Value OUTPUT :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    OUTPUT("OUTPUT");

    /** string representation */
    private final String value;

    /**
     * Creates a new MessageType Enumeration Literal
     *
     * @param v string representation
     */
    MessageType(final String v) {
        value = v;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @return string representation of this enum constant (value)
     */
    public final String value() {
        return this.value;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @see #value()
     * @return string representation of this enum constant (value)
     */
    @Override
    public final String toString() {
        return value();
    }

    /**
     * Return the MessageType enum constant corresponding to the given string representation (value)
     *
     * @param v string representation (value)
     *
     * @return MessageType enum constant
     *
     * @throws IllegalArgumentException if there is no matching enum constant
     */
    public final static MessageType fromValue(final String v) {
        for (MessageType c : MessageType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException("MessageType.fromValue : No enum const for the value : " + v);
    }

}
