/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.job;

import java.util.Date;

import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.IMetadataObjectContainer;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object RDBJobTarget :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_RDBJobTarget")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "RDBJobTarget.findById", query = "SELECT o FROM RDBJobTarget o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "RDBJobTarget.findByPublisherDID", query = "SELECT o FROM RDBJobTarget o WHERE o.identity.publisherDID = :publisherDID")

})

public class RDBJobTarget extends MetadataObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /** container gives the parent entity which owns a collection containing instances of this class */
    @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }, fetch = javax.persistence.FetchType.LAZY) @javax.persistence.JoinColumn(name = "containerId", referencedColumnName = "id", nullable = false)
    protected RDBJob container;

    /**
     * Attribute location :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "location", nullable = false)

    private String location;

    /**
     * Attribute targetType :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Enumerated(javax.persistence.EnumType.STRING) @javax.persistence.Column(name = "targetType", nullable = false)

    private RDBTargetType targetType;

    /**
     * Attribute resultNumber :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 , MaxLength : 2 )
     */

    @javax.persistence.Basic(optional = false) @javax.persistence.Column(name = "resultNumber", nullable = false, length = 2)

    private Short resultNumber;

    /**
     * Creates a new RDBJobTarget.
     */
    protected RDBJobTarget() {
        super();
    }

    /**
     * Creates a new RDBJobTarget for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public RDBJobTarget(final RDBJob pContainer) {
        super();
        this.setContainer(pContainer);
    }

    /**
     * Returns location Attribute
     * 
     * @return location Attribute
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Defines location Attribute
     * 
     * @param pLocation value to set
     */
    public void setLocation(final String pLocation) {
        this.location = pLocation;
    }

    /**
     * Returns targetType Attribute
     * 
     * @return targetType Attribute
     */
    public RDBTargetType getTargetType() {
        return this.targetType;
    }

    /**
     * Defines targetType Attribute
     * 
     * @param pTargetType value to set
     */
    public void setTargetType(final RDBTargetType pTargetType) {
        this.targetType = pTargetType;
    }

    /**
     * Returns resultNumber Attribute
     * 
     * @return resultNumber Attribute
     */
    public Short getResultNumber() {
        return this.resultNumber;
    }

    /**
     * Defines resultNumber Attribute
     * 
     * @param pResultNumber value to set
     */
    public void setResultNumber(final Short pResultNumber) {
        this.resultNumber = pResultNumber;
    }

    /**
     * Returns the Container Entity == 'Parent'.
     * 
     * @return the parent container Entity
     */
    public RDBJob getContainer() {
        return this.container;
    }

    @Override
    public IMetadataObjectContainer container() {
        return getContainer();
    }

    /**
     * Sets the Container Entity == 'Parent' ONLY.
     * 
     * @param pContainer the parent container
     */
    private void setContainerField(final RDBJob pContainer) {
        this.container = pContainer;
    }

    /**
     * Sets the Container Entity == 'Parent' and adds this to the appropriate collection on the container.
     *
     * @param pContainer the parent container CAN NOT BE NULL
     *
     * @throws IllegalStateException if pContainer is null !
     */
    protected void setContainer(final RDBJob pContainer) {
        if (pContainer == null) {
            throw new IllegalStateException("The parent container can not be null !");
        }
        setContainerField(pContainer);
        pContainer.addTarget(this);
    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final RDBJobTarget other = (RDBJobTarget) object;

            if (!areEquals(this.location, other.location)) {
                return false;
            }

            if (!areEquals(this.targetType, other.targetType)) {
                return false;
            }

            if (!areEquals(this.resultNumber, other.resultNumber)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if (PROPERTY_CONTAINER.equals(propertyName)) {
            return getContainer();
        }

        if ("location".equals(propertyName)) {
            return getLocation();
        }

        if ("targetType".equals(propertyName)) {
            return getTargetType();
        }

        if ("resultNumber".equals(propertyName)) {
            return getResultNumber();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if (PROPERTY_CONTAINER.equals(propertyName)) {
                setContainerField((RDBJob) pValue);
                return true;
            }

            if ("location".equals(propertyName)) {
                setLocation((String) pValue);
                return true;
            }

            if ("targetType".equals(propertyName)) {
                setTargetType((RDBTargetType) pValue);
                return true;
            }

            if ("resultNumber".equals(propertyName)) {
                setResultNumber((Short) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ RDBJobTarget");
        sb.append("={");

        sb.append("container=");
        if (getContainer() != null) {
            // short toString :
            MetadataElement.deepToString(sb, false, ids, getContainer());
        }
        sb.append(" | ");

        sb.append("location=");
        if (getLocation() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getLocation());
        }
        sb.append(", ");
        sb.append("targetType=");
        if (getTargetType() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getTargetType());
        }
        sb.append(", ");
        sb.append("resultNumber=");
        if (getResultNumber() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getResultNumber());
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && location != null;
        isOk = isOk && targetType != null;
        isOk = isOk && resultNumber != null;
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (location == null)
            sb.append("- atribute 'location' cannot be null\n");

        if (targetType == null)
            sb.append("- atribute 'targetType' cannot be null\n");

        if (resultNumber == null)
            sb.append("- atribute 'resultNumber' cannot be null\n");

        return sb.toString();
    }

}
