/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.job;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.MetadataRootEntityObject;
import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object RDBJob :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_RDBJob")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.DiscriminatorValue("RDBJob")

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "RDBJob.findById", query = "SELECT o FROM RDBJob o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "RDBJob.findByPublisherDID", query = "SELECT o FROM RDBJob o WHERE o.identity.publisherDID = :publisherDID")

})

public class RDBJob extends Job {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /**
     * Attribute inputSQL :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 , MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = false) @javax.persistence.Lob @javax.persistence.Column(name = "inputSQL", nullable = false)

    private String inputSQL;

    /**
     * Attribute sql : The SQL query sent to the database. If NULL, same as the inputSQL. ( Multiplicity : 0..1 ,
     * MaxLength : -1 )
     */

    @javax.persistence.Basic(fetch = javax.persistence.FetchType.EAGER, optional = true) @javax.persistence.Lob @javax.persistence.Column(name = "sql", nullable = true)

    private String sql;

    /**
     * Collection target :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..* )
     */

    @javax.persistence.OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.LAZY, mappedBy = "container", orphanRemoval = true)

    private List<RDBJobTarget> target = null;

    /**
     * Reference databaseContext :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "databaseContextId", referencedColumnName = "id", nullable = false)

    private DatabaseContext databaseContext = null;
    /**
     * "lazy" version of the databaseContext reference. Used by XML (un)marshallers to resolve possibly inderectly
     * referenced resource DatabaseContext.
     */

    @javax.persistence.Transient

    protected Reference p_databaseContext = null;

    /**
     * Creates a new RDBJob.
     */
    protected RDBJob() {
        super();
    }

    /**
     * Creates a new RDBJob for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public RDBJob(final TransientObjectManager pContainer) {
        super(pContainer);
    }

    /**
     * Returns inputSQL Attribute
     * 
     * @return inputSQL Attribute
     */
    public String getInputSQL() {
        return this.inputSQL;
    }

    /**
     * Defines inputSQL Attribute
     * 
     * @param pInputSQL value to set
     */
    public void setInputSQL(final String pInputSQL) {
        this.inputSQL = pInputSQL;
    }

    /**
     * Returns sql Attribute
     * 
     * @return sql Attribute
     */
    public String getSql() {
        return this.sql;
    }

    /**
     * Defines sql Attribute
     * 
     * @param pSql value to set
     */
    public void setSql(final String pSql) {
        this.sql = pSql;
    }

    /**
     * Returns target Collection
     * 
     * @return target Collection
     */
    public List<RDBJobTarget> getTarget() {
        return this.target;
    }

    /**
     * Defines target Collection
     * 
     * @param pTarget collection to set
     */
    public void setTarget(final List<RDBJobTarget> pTarget) {
        this.target = pTarget;
    }

    /**
     * Add a RDBJobTarget to the collection
     * 
     * @param pRDBJobTarget RDBJobTarget to add
     */
    public void addTarget(final RDBJobTarget pRDBJobTarget) {
        if (this.target == null) {
            this.target = new ArrayList<RDBJobTarget>();
        }

        this.target.add(pRDBJobTarget);
    }

    /**
     * Returns computeDomain Reference If the computeDomain variable is null but its "lazy" version p_computeDomain is
     * not, that lazy reference will be resolved to the actual object.
     * 
     * @return computeDomain Reference
     */
    public RDBComputeDomain getComputeDomain() {

        return (RDBComputeDomain) super.getComputeDomain();

    }

    /**
     * Defines computeDomain Reference
     * 
     * @param pComputeDomain reference to set
     */
    public void setComputeDomain(final RDBComputeDomain pComputeDomain) {

        super.setComputeDomain(pComputeDomain);

    }

    /**
     * Returns databaseContext Reference If the databaseContext variable is null but its "lazy" version
     * p_databaseContext is not, that lazy reference will be resolved to the actual object.
     * 
     * @return databaseContext Reference
     */
    public DatabaseContext getDatabaseContext() {

        if (this.databaseContext == null && this.p_databaseContext != null) {
            this.databaseContext = (DatabaseContext) resolve(this.p_databaseContext, DatabaseContext.class);
        }
        return this.databaseContext;

    }

    /**
     * Defines databaseContext Reference
     * 
     * @param pDatabaseContext reference to set
     */
    public void setDatabaseContext(final DatabaseContext pDatabaseContext) {

        this.databaseContext = pDatabaseContext;

    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final RDBJob other = (RDBJob) object;

            if (!areEquals(this.inputSQL, other.inputSQL)) {
                return false;
            }

            if (!areEquals(this.sql, other.sql)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if ("inputSQL".equals(propertyName)) {
            return getInputSQL();
        }

        if ("sql".equals(propertyName)) {
            return getSql();
        }

        if ("target".equals(propertyName)) {
            return getTarget();
        }

        if ("computeDomain".equals(propertyName)) {
            return getComputeDomain();
        }

        if ("databaseContext".equals(propertyName)) {
            return getDatabaseContext();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if ("inputSQL".equals(propertyName)) {
                setInputSQL((String) pValue);
                return true;
            }

            if ("sql".equals(propertyName)) {
                setSql((String) pValue);
                return true;
            }

            if ("computeDomain".equals(propertyName)) {
                setComputeDomain((RDBComputeDomain) pValue);
                return true;
            }

            if ("databaseContext".equals(propertyName)) {
                setDatabaseContext((DatabaseContext) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getComputeDomain() != null) {
            this.p_computeDomain = getComputeDomain().asReference();
            if (getStateFor(getComputeDomain()).isToBeMarshalled()) {
                getComputeDomain().setXmlId();
            }
        }

        if (getDatabaseContext() != null) {
            this.p_databaseContext = getDatabaseContext().asReference();
            if (getStateFor(getDatabaseContext()).isToBeMarshalled()) {
                getDatabaseContext().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_computeDomain = null;

        this.p_databaseContext = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        super.deepToString(sb, isDeep, ids);

        sb.append("\n[ RDBJob");
        sb.append("={");

        sb.append("inputSQL=");
        if (getInputSQL() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getInputSQL());
        }
        sb.append(", ");
        sb.append("sql=");
        if (getSql() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getSql());
        }
        sb.append(", ");
        sb.append("target=");
        if (getTarget() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getTarget());
        }
        sb.append(", ");
        sb.append("computeDomain.id=");
        if (getComputeDomain() != null) {
            getComputeDomain().getId();
        }
        sb.append(", ");
        sb.append("databaseContext.id=");
        if (getDatabaseContext() != null) {
            getDatabaseContext().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && inputSQL != null;
        isOk = isOk && (databaseContext != null || p_databaseContext != null);
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (inputSQL == null)
            sb.append("- atribute 'inputSQL' cannot be null\n");

        if (databaseContext == null && p_databaseContext == null)
            sb.append("- reference 'databaseContext' cannot be null\n");

        return sb.toString();
    }

}
