/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting the code
**/
package edu.jhu.job;

import javax.xml.bind.annotation.*;

/**
 * UML Enumeration RDBTargetType.
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public enum RDBTargetType {

    /**
     * Value TABLE :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    TABLE("TABLE"),

    /**
     * Value FILE_CSV :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_CSV("FILE_CSV"),

    /**
     * Value FILE_VOTABLE :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_VOTABLE("FILE_VOTABLE"),

    /**
     * Value FILE_FITS :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_FITS("FILE_FITS"),

    /**
     * Value FILE_JSON :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_JSON("FILE_JSON"),

    /**
     * Value FILE_TSV :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_TSV("FILE_TSV"),

    /**
     * Value FILE_BSV :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    FILE_BSV("FILE_BSV");

    /** string representation */
    private final String value;

    /**
     * Creates a new RDBTargetType Enumeration Literal
     *
     * @param v string representation
     */
    RDBTargetType(final String v) {
        value = v;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @return string representation of this enum constant (value)
     */
    public final String value() {
        return this.value;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @see #value()
     * @return string representation of this enum constant (value)
     */
    @Override
    public final String toString() {
        return value();
    }

    /**
     * Return the RDBTargetType enum constant corresponding to the given string representation (value)
     *
     * @param v string representation (value)
     *
     * @return RDBTargetType enum constant
     *
     * @throws IllegalArgumentException if there is no matching enum constant
     */
    public final static RDBTargetType fromValue(final String v) {
        for (RDBTargetType c : RDBTargetType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException("RDBTargetType.fromValue : No enum const for the value : " + v);
    }

}
