/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting the code
**/
package edu.jhu.job;

import javax.xml.bind.annotation.*;

/**
 * UML Enumeration RDBVendor.
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public enum RDBVendor {

    /**
     * Value SQLSERVER :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    SQLSERVER("SQLSERVER"),

    /**
     * Value MYSQL :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    MYSQL("MYSQL"),

    /**
     * Value POSTGRES :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    POSTGRES("POSTGRES"),

    /**
     * Value ORACLE :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    ORACLE("ORACLE"),

    /**
     * Value DB2 :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    DBTWO("DB2"),

    /**
     * Value SYBASE :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    SYBASE("SYBASE");

    /** string representation */
    private final String value;

    /**
     * Creates a new RDBVendor Enumeration Literal
     *
     * @param v string representation
     */
    RDBVendor(final String v) {
        value = v;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @return string representation of this enum constant (value)
     */
    public final String value() {
        return this.value;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @see #value()
     * @return string representation of this enum constant (value)
     */
    @Override
    public final String toString() {
        return value();
    }

    /**
     * Return the RDBVendor enum constant corresponding to the given string representation (value)
     *
     * @param v string representation (value)
     *
     * @return RDBVendor enum constant
     *
     * @throws IllegalArgumentException if there is no matching enum constant
     */
    public final static RDBVendor fromValue(final String v) {
        for (RDBVendor c : RDBVendor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException("RDBVendor.fromValue : No enum const for the value : " + v);
    }

}
