/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting it.
**/

package edu.jhu.job;

import java.util.Date;

import java.util.Map;
import org.ivoa.dm.model.MetadataElement;
import org.ivoa.dm.model.IMetadataObjectContainer;
import org.ivoa.dm.model.Reference;
import org.ivoa.dm.model.TransientObjectManager;
import org.ivoa.dm.model.MetadataObject;
import org.ivoa.dm.model.IMetadataObjectContainer;

import edu.jhu.file.UserVolume;

import static edu.jhu.ModelVersion.LAST_MODIFICATION_DATE;

/**
 * UML Object RequiredUserVolume :
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */

@javax.persistence.Entity @javax.persistence.Table(name = "t_RequiredUserVolume")

@javax.persistence.Inheritance(strategy = javax.persistence.InheritanceType.JOINED) @javax.persistence.DiscriminatorColumn(name = "DTYPE", discriminatorType = javax.persistence.DiscriminatorType.STRING, length = 32)

@javax.persistence.NamedQueries({
        @javax.persistence.NamedQuery(name = "RequiredUserVolume.findById", query = "SELECT o FROM RequiredUserVolume o WHERE o.id = :id"),
        @javax.persistence.NamedQuery(name = "RequiredUserVolume.findByPublisherDID", query = "SELECT o FROM RequiredUserVolume o WHERE o.identity.publisherDID = :publisherDID")

})

public class RequiredUserVolume extends MetadataObject {

    /** serial uid = last modification date of the UML model. */
    private static final long serialVersionUID = LAST_MODIFICATION_DATE;

    /** jpaVersion gives the current version number for that entity (used by pessimistic / optimistic locking in JPA) */
    @javax.persistence.Version() @javax.persistence.Column(name = "OPTLOCK")
    protected int jpaVersion;

    /** container gives the parent entity which owns a collection containing instances of this class */
    @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }, fetch = javax.persistence.FetchType.LAZY) @javax.persistence.JoinColumn(name = "containerId", referencedColumnName = "id", nullable = false)
    protected Job container;

    /**
     * Attribute pathOnComputeDomain :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "pathOnComputeDomain", nullable = true)

    private String pathOnComputeDomain;

    /**
     * Attribute needsWriteAccess :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 0..1 )
     */

    @javax.persistence.Basic(optional = true) @javax.persistence.Column(name = "needsWriteAccess", nullable = true)

    private Boolean needsWriteAccess;

    /**
     * Reference userVolume :
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     * ( Multiplicity : 1 )
     */

    @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = {
            javax.persistence.CascadeType.PERSIST, javax.persistence.CascadeType.MERGE,
            javax.persistence.CascadeType.REFRESH }) @javax.persistence.JoinColumn(name = "userVolumeId", referencedColumnName = "id", nullable = false)

    private UserVolume userVolume = null;
    /**
     * "lazy" version of the userVolume reference. Used by XML (un)marshallers to resolve possibly inderectly referenced
     * resource UserVolume.
     */

    @javax.persistence.Transient

    protected Reference p_userVolume = null;

    /**
     * Creates a new RequiredUserVolume.
     */
    protected RequiredUserVolume() {
        super();
    }

    /**
     * Creates a new RequiredUserVolume for the given Container Entity.
     *
     * The Parent Container CAN NOT BE NULL
     *
     * @param pContainer the parent container CAN NOT BE NULL
     */
    public RequiredUserVolume(final Job pContainer) {
        super();
        this.setContainer(pContainer);
    }

    /**
     * Returns pathOnComputeDomain Attribute
     * 
     * @return pathOnComputeDomain Attribute
     */
    public String getPathOnComputeDomain() {
        return this.pathOnComputeDomain;
    }

    /**
     * Defines pathOnComputeDomain Attribute
     * 
     * @param pPathOnComputeDomain value to set
     */
    public void setPathOnComputeDomain(final String pPathOnComputeDomain) {
        this.pathOnComputeDomain = pPathOnComputeDomain;
    }

    /**
     * Returns needsWriteAccess Attribute
     * 
     * @return needsWriteAccess Attribute
     */
    public Boolean getNeedsWriteAccess() {
        return this.needsWriteAccess;
    }

    /**
     * Defines needsWriteAccess Attribute
     * 
     * @param pNeedsWriteAccess value to set
     */
    public void setNeedsWriteAccess(final Boolean pNeedsWriteAccess) {
        this.needsWriteAccess = pNeedsWriteAccess;
    }

    /**
     * Returns userVolume Reference If the userVolume variable is null but its "lazy" version p_userVolume is not, that
     * lazy reference will be resolved to the actual object.
     * 
     * @return userVolume Reference
     */
    public UserVolume getUserVolume() {

        if (this.userVolume == null && this.p_userVolume != null) {
            this.userVolume = (UserVolume) resolve(this.p_userVolume, UserVolume.class);
        }
        return this.userVolume;

    }

    /**
     * Defines userVolume Reference
     * 
     * @param pUserVolume reference to set
     */
    public void setUserVolume(final UserVolume pUserVolume) {

        this.userVolume = pUserVolume;

    }

    /**
     * Returns the Container Entity == 'Parent'.
     * 
     * @return the parent container Entity
     */
    public Job getContainer() {
        return this.container;
    }

    @Override
    public IMetadataObjectContainer container() {
        return getContainer();
    }

    /**
     * Sets the Container Entity == 'Parent' ONLY.
     * 
     * @param pContainer the parent container
     */
    private void setContainerField(final Job pContainer) {
        this.container = pContainer;
    }

    /**
     * Sets the Container Entity == 'Parent' and adds this to the appropriate collection on the container.
     *
     * @param pContainer the parent container CAN NOT BE NULL
     *
     * @throws IllegalStateException if pContainer is null !
     */
    protected void setContainer(final Job pContainer) {
        if (pContainer == null) {
            throw new IllegalStateException("The parent container can not be null !");
        }
        setContainerField(pContainer);
        pContainer.addUserVolume(this);
    }

    /**
     * Returns Jpa version for optimistic locking.
     * 
     * @return jpa version number
     */
    protected int getJpaVersion() {
        return this.jpaVersion;
    }

    /**
     * Returns equals from id attribute here. Child classes can override this method to allow deep equals with
     * attributes / references / collections
     *
     * @param object the reference object with which to compare.
     * @param isDeep true means to call hashCode(sb, true) for all attributes / references / collections which are
     * MetadataElement implementations
     *
     * @return <code>true</code> if this object is the same as the obj argument; <code>false</code> otherwise.
     */
    @Override
    public boolean equals(final Object object, final boolean isDeep) {
        /* identity, nullable, class and identifiers checks */
        if (!(super.equals(object, isDeep))) {
            return false;
        }

        /* do check values (attributes / references / collections) */

        if (isDeep) {

            final RequiredUserVolume other = (RequiredUserVolume) object;

            if (!areEquals(this.pathOnComputeDomain, other.pathOnComputeDomain)) {
                return false;
            }

            if (!areEquals(this.needsWriteAccess, other.needsWriteAccess)) {
                return false;
            }

        }

        return true;
    }

    /**
     * Returns the property value given the property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @return property value or null if unknown or not defined
     */
    @Override
    public Object getProperty(final String propertyName) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return null;
        }
        // second : search in parent classes (maybe null) :
        Object res = super.getProperty(propertyName);

        if (PROPERTY_CONTAINER.equals(propertyName)) {
            return getContainer();
        }

        if ("pathOnComputeDomain".equals(propertyName)) {
            return getPathOnComputeDomain();
        }

        if ("needsWriteAccess".equals(propertyName)) {
            return getNeedsWriteAccess();
        }

        if ("userVolume".equals(propertyName)) {
            return getUserVolume();
        }

        return res;
    }

    /**
     * Sets the property value to the given property name. Can be any property (internal, attribute, reference,
     * collection) and all type must be supported (dataType, objectType, enumeration)
     *
     * @param propertyName name of the property (like in UML model)
     *
     * @param pValue to be set
     * 
     * @return true if property has been set
     */
    @Override
    public boolean setProperty(final String propertyName, final Object pValue) {
        // first : checks if propertyName is null or empty :
        if (propertyName == null) {
            return false;
        }
        // second : search in parent classes (maybe null) :
        boolean res = super.setProperty(propertyName, pValue);

        if (!res) {

            if (PROPERTY_CONTAINER.equals(propertyName)) {
                setContainerField((Job) pValue);
                return true;
            }

            if ("pathOnComputeDomain".equals(propertyName)) {
                setPathOnComputeDomain((String) pValue);
                return true;
            }

            if ("needsWriteAccess".equals(propertyName)) {
                setNeedsWriteAccess((Boolean) pValue);
                return true;
            }

            if ("userVolume".equals(propertyName)) {
                setUserVolume((UserVolume) pValue);
                return true;
            }

        }

        return res;
    }

    /**
     * Sets all Reference fields to their appropriate value.<br/>
     */
    @Override
    protected void prepareReferencesForMarshalling() {
        super.prepareReferencesForMarshalling();

        if (getUserVolume() != null) {
            this.p_userVolume = getUserVolume().asReference();
            if (getStateFor(getUserVolume()).isToBeMarshalled()) {
                getUserVolume().setXmlId();
            }
        }

    }

    /**
     * Resets all Reference fields to null.<br/>
     */
    @Override
    protected void resetReferencesAfterMarshalling() {
        super.prepareReferencesForMarshalling();

        this.p_userVolume = null;

    }

    /**
     * Puts the string representation in the given string buffer : <br>
     * "Type =[class name @ hashcode] : { field name = field value , ...}"
     *
     * @param sb given string buffer to fill
     * @param isDeep true means to call deepToString(sb, true, ids) for all attributes / references / collections which
     * are MetadataElement implementations
     * @param ids identity map to avoid cyclic loops
     *
     * @return stringbuffer the given string buffer filled with the string representation
     */
    @Override
    protected StringBuilder deepToString(final StringBuilder sb, final boolean isDeep,
            final Map<MetadataElement, Object> ids) {

        sb.append("\n[ RequiredUserVolume");
        sb.append("={");

        sb.append("container=");
        if (getContainer() != null) {
            // short toString :
            MetadataElement.deepToString(sb, false, ids, getContainer());
        }
        sb.append(" | ");

        sb.append("pathOnComputeDomain=");
        if (getPathOnComputeDomain() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getPathOnComputeDomain());
        }
        sb.append(", ");
        sb.append("needsWriteAccess=");
        if (getNeedsWriteAccess() != null) {
            MetadataElement.deepToString(sb, isDeep, ids, getNeedsWriteAccess());
        }
        sb.append(", ");
        sb.append("userVolume.id=");
        if (getUserVolume() != null) {
            getUserVolume().getId();
        }

        return sb.append("} ]");

    }

    public boolean isValid() {
        if (!super.isValid())
            return false;
        boolean isOk = true;
        isOk = isOk && (userVolume != null || p_userVolume != null);
        return isOk;
    }

    public String validationErrors() {
        StringBuffer sb = new StringBuffer(super.validationErrors());

        if (userVolume == null && p_userVolume == null)
            sb.append("- reference 'userVolume' cannot be null\n");

        return sb.toString();
    }

}
