apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-racm-db
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: racm-db
type: Opaque
data:
  password: {{ required "password required!" .Values.racmDb.password | b64enc | quote }}
