{{ if and .Values.keycloak.enabled (not .Values.keycloak.url) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-keycloak-admin-pass
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  password: {{ required "password required!" .Values.keycloak.app.adminPass | b64enc | quote }}
{{ end -}}
