/**
This code was originally automatically generated from the UML model in
https://github.com/sciserver/resource-management/blob/master/vo-urp/RACM_v1.xml
using the VO-URP tool, https://github.com/sciserver/vo-urp. 
It is now included in the code-base and will no longer be 
generated automatically. You can edit this file, but be aware
of its origins when interpreting the code
**/
package edu.jhu.user;

import javax.xml.bind.annotation.*;

/**
 * UML Enumeration MemberStatus.
 *
 * 
 * TODO : Missing description : please, update your UML model asap.
 *
 * 
 * @author generated by VO-URP tools VO-URP Home
 * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
 */
public enum MemberStatus {

    /**
     * Value INVITED :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    INVITED("INVITED"),

    /**
     * Value ACCEPTED :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    ACCEPTED("ACCEPTED"),

    /**
     * Value DECLINED :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    DECLINED("DECLINED"),

    /**
     * Value WITHDRAWN :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    WITHDRAWN("WITHDRAWN"),

    /**
     * Value OWNER :
     * 
     * 
     * TODO : Missing description : please, update your UML model asap.
     * 
     */
    OWNER("OWNER");

    /** string representation */
    private final String value;

    /**
     * Creates a new MemberStatus Enumeration Literal
     *
     * @param v string representation
     */
    MemberStatus(final String v) {
        value = v;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @return string representation of this enum constant (value)
     */
    public final String value() {
        return this.value;
    }

    /**
     * Return the string representation of this enum constant (value)
     * 
     * @see #value()
     * @return string representation of this enum constant (value)
     */
    @Override
    public final String toString() {
        return value();
    }

    /**
     * Return the MemberStatus enum constant corresponding to the given string representation (value)
     *
     * @param v string representation (value)
     *
     * @return MemberStatus enum constant
     *
     * @throws IllegalArgumentException if there is no matching enum constant
     */
    public final static MemberStatus fromValue(final String v) {
        for (MemberStatus c : MemberStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException("MemberStatus.fromValue : No enum const for the value : " + v);
    }

}
