{{- if not .Values.compute.certSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sciserver.fullname" . }}-compute-certs
  labels:
    app.kubernetes.io/name: {{ include "sciserver.name" . }}
    helm.sh/chart: {{ include "sciserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: compute
type: Opaque
{{- end }}
